when@dev:
    _pentatrion_vite_build1:
        path: /build-1/{path}
        defaults:
            _controller: Pentatrion\ViteBundle\Controller\ViteController::proxyBuild
            configName: config1
        requirements:
            path: ".+"

    _pentatrion_vite_build2:
        path: /build-2/{path}
        defaults:
            _controller: Pentatrion\ViteBundle\Controller\ViteController::proxyBuild
            configName: config2
        requirements:
            path: ".+"

    _profiler_vite:
        path: /_profiler/vite
        defaults:
            _controller: Pentatrion\ViteBundle\Controller\ProfilerController::info
